version: '3'
services:
  #MySQL用コンテナ
  mysql:
    container_name: db
    image: mariadb:10.4
    volumes:
      - ./data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=todo
        - MYSQL_USER=todo
        - MYSQL_PASSWORD=todo  
    ports:
        - 3306:3306
  #php用コンテナ
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./source:/var/www/html
      - .php/vhosts.conf:/etc/apache2/conf-enabled/vhosts.conf
    ports:
      - 8080:80
    depends_on:
      - mysql
